### ISSUE TITLE
Lacks of Database Seeders for reference.

### ISSUE THREAD

**Issue by wanadzmi** [phpreel/phpreel#7]
Hi! can you provide db seeder for this project?

**Comment by reelsoftware** [comment]
Hi!
At the moment seeders are not available. There is a backlog of things to do: laravel packages, tests, seeders, docker deployment, and at the same time working on version 0.2.0 which will have theme support. It's just one person (me) working part-time on the project, but I hope that if someone finds the project suitable for their needs, they will fork it and add the "missing piece". Thank you! Glad you find the project interesting.

**Comment by wanadzmi** [comment]
i see.. but tbh, default seeder for table "settings" and table "subscription_types" need to be added by default because it is very crucial in order to make Subscription works for you project. Luckily i able to solved it myself by reading your controller. TQ anyway. You project is great! Simple and clean.

**Comment by reelsoftware** [comment]
These seeders for settings and subscription_types are actually implemented in the installer. They probably did not run because of the bug that you encountered...I am trying to fix it but it's difficult because I don't encounter the issues you faced in my tests. It might be because we are using different web servers. Could you please tell me what web server did you installed the app on?
